language: node_js
node_js:
  - 8
env:
  - CXX=g++-7 && CC=gcc-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7
after_success: npm run-script build
